---
date: "April 22, 2019"
output: html_document
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
</style>

## Staffing Bonus {.tabset .tabset-fade}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
load("C:/Users/123894/Documents/Pay Codes Project/Workspace/Staffing bonus DFs.RData")
library(DT)
library(htmltools)  ## needed for tags that are used to create table headers (e.g., 2016 Hours)
# library(scales)     ## for percent format
library(dplyr)
library(kableExtra)
library(plotly)
```


```{r}
```


### Usage Statistics
```{r}

## maybe add here total $ spent on 481 each year?
kable(table_totWGHR,
      col.names = c(" ",
                    "2016",
                    "2017",
                    "2018"),
      align = rep('c',1),
      caption = "Table 1 - Staffing Bonus Expense and Hours for 2016-2018") %>%
  kable_styling(full_width = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  kable_styling(font_size = 18) %>%
  column_spec(1, bold = T, border_right = T, width = "15em") %>%
  column_spec(2:4, width = "8em")
```

<br>
<br>
<br>
<br>


```{r}
## kable with unique dept, pos, and assoc use of 481 from 16-18

kable(genUse_table,
      col.names = c(" ",
                    "2016",
                    "2017",
                    "2018"),
      align = rep('r',1),
      caption = "Table 2") %>%
  kable_styling(full_width = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  kable_styling(font_size = 18) %>%
  column_spec(1, bold = T, border_right = T, width = "33em") %>%
  column_spec(2:4, width = "5em")
```

<br>
<br>
<br>
<br>


```{r}
## number of cases where staffing bonus hours < 4
kable(table_hrsLT4,
      col.names = c(" ",
                    "2016",
                    "2017",
                    "2018"),
      align = rep('r',1),
      caption = "Table 3") %>%
  kable_styling(full_width = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  kable_styling(font_size = 18) %>%
  column_spec(1, bold = T, border_right = T, width = "33em") %>%
  column_spec(2:4, width = "5em")
```



```{r}
library(formattable)

## rounds sum col to whole number
table_481byPL <- table_481byPL %>%
  mutate_at(vars(starts_with("Hours")),
            funs(round(., 0)))


# add currency format to wages in df  (load 'formattable' package)
table_481byPL$Wages16 <- currency(table_481byPL$Wages16, digits = 0L)
table_481byPL$Wages17 <- currency(table_481byPL$Wages17, digits = 0L)
table_481byPL$Wages18 <- currency(table_481byPL$Wages18, digits = 0L)

```



### By Process Level
```{r}

## wages and hours for 481 by process level
kable(table_481byPL,
      col.names = c(" ",
                    "Company Name",
                    "Wages",
                    "Hours",
                    "Wages",
                    "Hours",
                    "Wages",
                    "Hours"), format.args = list(big.mark = ",")) %>%
  kable_styling(full_width = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  add_header_above(c(" " = 2, "2016" = 2, "2017" = 2, "2018" = 2)) %>%
  kable_styling(font_size = 18) %>%
  column_spec(3:8, width = "6em") %>%
  column_spec(1, width = "5em") %>%
  column_spec(2, width = "12em")
```


### Plot
```{r, out.width="100%"}
plot_ly(data = bymo_481wages, type = 'scatter') %>%
  add_lines(x = ~month, y = ~Wages16, name = '2016', mode = 'lines+markers', line = list(color = 'rgb(221,98,89)')) %>%
  add_lines(x = ~month, y = ~Wages17, name = '2017', mode = 'lines+markers', line = list(color = 'rgb(115,130,243)')) %>%
  add_lines(x = ~month, y = ~Wages18, name = '2018', mode = 'lines+markers', line = list(color = 'rgb(45,112,80)')) %>%
  layout(
    title = 'Wages ($) for Staffing Bonus',
    yaxis = list(side = 'left', title = 'Wages ($)'),
    xaxis = list(title = "",
                 showgrid = F,
                 showticklabels = T,
                 ticks = 'inside',
                 tickwidth = 1,
                 ticklen = 10,
                 tickcolor = 'rgb(204,204,204')
  )
```

<br>
<br>
<br>

```{r, out.width="100%"}
## plot for call worked comparison
plot_ly(data = bymo_CWwages, type = 'scatter') %>%
  add_lines(x = ~month, y = ~Wages16, name = '2016', mode = 'lines+markers', line = list(color = 'rgb(221,98,89)')) %>%
  add_lines(x = ~month, y = ~Wages17, name = '2017', mode = 'lines+markers', line = list(color = 'rgb(115,130,243)')) %>%
  add_lines(x = ~month, y = ~Wages18, name = '2018', mode = 'lines+markers', line = list(color = 'rgb(45,112,80)')) %>%
  layout(
    title = 'Wages ($) for Call Worked',
    yaxis = list(side = 'left', title = 'Wages ($)'),
    xaxis = list(title = "",
                 showgrid = F,
                 showticklabels = T,
                 ticks = 'inside',
                 tickwidth = 1,
                 ticklen = 10,
                 tickcolor = 'rgb(204,204,204')
  )
```

<br>
<br>
<br>

```{r, out.width="100%"}
## PAL Plot
plot_ly(data = bymo_PALwages, type = 'scatter') %>%
  add_lines(x = ~month, y = ~Wages16, name = '2016', mode = 'lines+markers', line = list(color = 'rgb(221,98,89)')) %>%
  add_lines(x = ~month, y = ~Wages17, name = '2017', mode = 'lines+markers', line = list(color = 'rgb(115,130,243)')) %>%
  add_lines(x = ~month, y = ~Wages18, name = '2018', mode = 'lines+markers', line = list(color = 'rgb(45,112,80)')) %>%
  layout(
    title = 'Wages ($) for PAL',
    yaxis = list(side = 'left', title = 'Wages ($)'),
    xaxis = list(title = "",
                 showgrid = F,
                 showticklabels = T,
                 ticks = 'inside',
                 tickwidth = 1,
                 ticklen = 10,
                 tickcolor = 'rgb(204,204,204')
  )
```






```{r}
# library(scales)     ## for percent format

## make company var a factor so that col filter in DT will use selectize inputs instead of range slider
stfbonus_bydept$PL <- as.factor(stfbonus_bydept$PL)
stfbonus_bydept$Dept <- as.factor(stfbonus_bydept$Dept)

## order by Wages 2018
stfbonus_bydept <- stfbonus_bydept[order(stfbonus_bydept$Wages18, decreasing = T),]

## rounds columns to whole number
stfbonus_bydept <- stfbonus_bydept %>%
  mutate_at(vars(Wages16, Wages17, Wages18),
            funs(round(., 0)))

```
### By Department - Wages ($) 
```{r set-options}
options(width = 200)

## staffing bonus wages and hours with DEPARTMENT ONLY
# library(scales)     ## for percent format

datatable(stfbonus_bydept[,c(1:3,5,11,7,12,9,13)],
          colnames = c("Company",
                       "Department",
                       "Name",
                       "Wages ($)",
                       "% of Total",
                       "Wages ($)",
                       "% of Total",
                       "Wages ($)",
                       "% of Total"),
          rownames = FALSE,
          extensions = 'FixedHeader',
          options = list(fixedHeader = TRUE),
          width = '1500px',
          filter = 'top',
          container = withTags(table(
            class = 'display',
            thead(
              tr(
                th(colspan = 3, ' '),
                th(colspan = 2, '2016'),
                th(colspan = 2, '2017'),
                th(colspan = 2, '2018')
              ),
              tr(
                lapply(rep(c('Company','Department', 'Name', 'Wages ($)','% of Total', 'Wages ($)','% of Total', 'Wages ($)', '% of Total'), 1), th)
              )
            )
          ))
)

```





```{r}

## make company var a factor so that col filter in DT will use selectize inputs instead of range slider
stfbonus_bypos$PL <- as.factor(stfbonus_bypos$PL)
stfbonus_bypos$Dept <- as.factor(stfbonus_bypos$Dept)

## order by Wages 2018
stfbonus_bypos <- stfbonus_bypos[order(stfbonus_bypos$Wages18, decreasing = T),]

## rounds columns to whole number
stfbonus_bypos <- stfbonus_bypos %>%
  mutate_at(vars(Wages16, Wages17, Wages18),
            funs(round(., 0)))

```
### By Position - Wages ($) 
```{r}
options(width = 200)

## staffing bonus wages and hours with POSITION

datatable(stfbonus_bypos[,c(1:3,5,6,12,8,13,10,14)],
          colnames = c("Company",
                       "Department",
                       "Name",
                       "Position",
                       "Wages ($)",
                       "% of Total",
                       "Wages ($)",
                       "% of Total",
                       "Wages ($)",
                       "% of Total"),
          rownames = FALSE,
          extensions = 'FixedHeader',
          options = list(fixedHeader = TRUE),
          width = '1500px',
          filter = 'top',
          container = withTags(table(
            class = 'display',
            thead(
              tr(
                th(colspan = 4, ' '),
                th(colspan = 2, '2016'),
                th(colspan = 2, '2017'),
                th(colspan = 2, '2018')
              ),
              tr(
                lapply(rep(c('Company','Department', 'Name','Position', 'Wages ($)','% of Total',  'Wages ($)','% of Total', 'Wages ($)', '% of Total'), 1), th)
              )
            )
          ))
)

```






